[package]
name = "sofia-ui-layer"
version.workspace = true
edition.workspace = true

[dependencies]
futures-util.workspace = true
gpui-kit.workspace = true
markdown = "1.0.0"
merman = "0.8.0"
open.workspace = true
pulldown-cmark.workspace = true
resvg = "0.45.1"
serde_json.workspace = true
sofia-config.workspace = true
sofia-content.workspace = true
sofia-protocol.workspace = true
tokio.workspace = true
tokio-util.workspace = true
usvg = "0.45.1"
