[package]
name = "sofia-mcp"
version.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
futures-util.workspace = true
rmcp = { workspace = true, features = ["server", "transport-io"] }
serde.workspace = true
serde_json.workspace = true
sofia-content.workspace = true
sofia-protocol.workspace = true
tokio.workspace = true
tokio-util.workspace = true
uuid.workspace = true
